#!/bin/bash
set -e

# Получаем последнюю введённую команду
LAST_COMMAND=$(ps -o args= $PPID)

# Проверяем, была ли введена команда "subtree push" или "st push"
if [[ "$LAST_COMMAND" == *"push shared-types"* ]]; then
    exit 0
fi

    # Текущая ветка
BRANCH=$(git rev-parse --abbrev-ref HEAD)
echo "💡 Текущая ветка: $BRANCH"


# Список защищённых веток (добавь сюда нужные)
PROTECTED_BRANCHES=("stage" "prod" "main")

# Проверяем, является ли текущая ветка защищённой
for PROTECTED in "${PROTECTED_BRANCHES[@]}"; do
    if [[ "$BRANCH" == "$PROTECTED" ]]; then
        echo "❌ Ошибка: Ветка $BRANCH защищена! Прямой push запрещён."
        echo "🔒 Разрешены только Merge Requests."
        exit 1
    fi
done

# Файл для флага, который проверяет, был ли уже выполнен push в shared-types
FLAG_FILE=".git/subtree_push_in_progress"
if ! [ -f $FLAG_FILE ]; then
    
    # Проверяем, есть ли изменения в shared-types
    if ! git diff --quiet --exit-code shared-types/ || ! git diff --cached --quiet --exit-code shared-types/ || ! git diff --quiet --exit-code origin/$BRANCH shared-types/; then
        touch $FLAG_FILE
        echo "🔄 Обнаружены изменения в shared-types. Выполнение push для subtree..."
        
        # Выполняем push для subtree
        if git subtree push --prefix=shared-types shared-types "$BRANCH"; then
            echo "✅ Успешно выполнен push в shared-types на ветку: $BRANCH"
        else
            echo "❌ Ошибка при выполнении push в shared-types"
            rm -f $FLAG_FILE
            exit 1
        fi
        
        # Удаляем файл флага
        rm -f $FLAG_FILE
    else
        echo "💡 Изменений в shared-types нет"
    fi

    exit 0
fi

# Проверка на наличие изменений в коммитах перед основным push
remote="$1"
url="$2"

zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')

while read local_ref local_oid remote_ref remote_oid
do
    if test "$local_oid" = "$zero"
    then
        # Handle delete
        :
    else
        if test "$remote_oid" = "$zero"
        then
            # New branch, examine all commits
            range="$local_oid"
        else
            # Update to existing branch, examine new commits
            range="$remote_oid..$local_oid"
        fi

        # Check for WIP commit
        commit=$(git rev-list -n 1 --grep '^WIP' "$range")
        if test -n "$commit"
        then
            echo >&2 "Найден WIP коммит в $local_ref, не выполняем push"
            exit 1
        fi
    fi
done

exit 0